<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <IsAotCompatible>true</IsAotCompatible>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <!-- For SQLitePCLRaw -->
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Mofucat.SqliteConfiguration</PackageId>
    <Title>Mofucat.SqliteConfiguration</Title>
    <Description>.NET Configuration Extensions for SQLite.</Description>
    <PackageTags>configuration</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
  </ItemGroup>

</Project>
